version: '3.9'  # Specify Docker Compose version

services:
  weather-api:
    build: .  # Build the image from the Dockerfile in the current directory
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    restart: unless-stopped  # Restart the container unless manually stopped

